#Any time we are going to use docker we need sudo permissions
sudo: required
#This tells Travis cli that we need docker to be pre-installed
services: 
    - docker

#This is going to execute a series of commands before running
#our tests
before_install:
    - docker build -t anvsunil/docker-react -f Dockerfile.dev .

# The script command will actually contain the list of commands
# for testing
script:
    - docker run -e CI=true anvsunil/docker-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    #app is the name of the given EBS  
    app: "docker"
    env: "Docker-env"
    #bucket name is the name of the S3 bucket that was automatically created
    bucket_name: "elasticbeanstalk-us-west-2-264024450650"
    #bucket path should be same as app name
    bucket_path: "docker"
    on: 
        #Only when changes are pushed to master then only deploy
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

